#!/bin/csh

# this definition is optional
setenv EPICS_DISPLAY_PATH .

# MUST be defined before calling ./setup_epics_common
setenv EPICS_APP /home/oxygen/MOONEY/epics/synApps/support/lsredis
setenv EPICS_APP_ADL_DIR ${EPICS_APP}/lsredisApp/op/adl

# Allow script to be run from any directory
cd ${EPICS_APP}

# define environment variables for MEDM and Probe
source ./setup_epics_common

echo ${EPICS_DISPLAY_PATH}
cd ${EPICS_APP_ADL_DIR}

# start MEDM
medm lsredis.adl &
